package com.example.sipentas.models

data class AssesmentRow (
    val tanggal:String,
    val petugas:String,
    val status_dtks:String,
    val created_at:String,
    val nama_bpk:String,
    val nama_ibu:String,
    val nama_wali:String,
    val penghasilan:String,
    val catatan:String,
    val foto_rumah:String,
    val foto_kondisi_fisik:String,
    val foto_kk:String,
    val foto_ktp:String,
    val long:String,
    val lat:String,
    val id_kerja_ortu:Int,
    val id_satker:Int,
    val id_user:Int,
    val nama_user:String,
    val id_pendidikan:Int,
    val nama_pendidikan:String,
    val id_sumber_kasus:Int,
    val nama_sumber_kasus:String,
    val id_pekerjaan:Int,
    val nama_pekerjaan:String,
    val id_pm:Int,
    val nama_pm:String,
    val nik_pm:String,
    val id_status_ortu:Int,
    val nama_status_ortu:String,
    val id_tempat_tinggal:Int,
    val nama_tempat_tinggal:String
        )
